jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    NODE_VERSION: 10.13.0
    SPRING_OUTPUT_ANSI_ENABLED: NEVER
    SPRING_JPA_SHOW_SQL: false
    JHI_DISABLE_WEBPACK_LOGS: true

  steps:
  #----------------------------------------------------------------------
  # Install all tools and check configuration
  #----------------------------------------------------------------------
  - task: NodeTool@0
    inputs:
      versionSpec: '10.13.0'
    displayName: 'TOOLS: install Node.js'
  - script: sudo npm install -g npm
    displayName: 'TOOLS: update NPM'
  - script: sudo /etc/init.d/mysql stop
    displayName: 'TOOLS: stop MySQL'
  #----------------------------------------------------------------------
  # Tests
  #----------------------------------------------------------------------
  - script: npm install
    displayName: 'INSTALL: launch npm install'
  - script: |
      chmod +x gradlew
      ./gradlew clean test
    displayName: 'TESTS: backend'
  - script: ./gradlew npm_run_test-ci -PnodeInstall --no-daemon
    displayName: 'TESTS: frontend'
  - script: ./gradlew bootWar -Pprod -x test
    displayName: 'TESTS: packaging'
